= 功能点分析法
:toc:
:toc-title: 目录
:toclevels: 4
:sectnums:

功能点分析法（Function Point Analysis，FPA），针对用户功能、性能的需求进行度量，具有可在项目早期进行度量，不依赖于项目的语言和技术等。

评估步骤：

. 收集可得的文档
. 确定计数范围和边界，识别功能用户需求
. 度量数据功能/度量事务功能
. 计算功能规模
. 编写文档报告结果

== 模型说明

在FPA中，核心分为5个模型：

- 外部输入处理EI（External Input），是获取数据的过程，对终端用户的输入进行相关的处理。其首要目的（Primary Intent，简称 PI） 是维护一个或多个ILFs 或者去改变系统行为。
- 外部查询处理EQ（External Inquiry），针对终端用户的查询情况，输出相应的检索结果。其首要目的（PI）是通过从一个 ILF 或EIF 检索数据或控制信息，呈现信息给用户。
- 外部输出处理EO（External Output），是反馈数据的过程，完成对票据、报表等的输出。其首要目的（PI）是通过处理逻辑呈现信息给用户，并非或者另外检索数据或控制信息。
- 内部逻辑文件ILF（Internal Logical File），在信息系统内部，为了完成相关功能使用的逻辑文件，包括顺序文件、数据库表、临时文件等。
- 外部文件EIF（External Interface File），该系统和外部其他信息系统为交换数据而用的接口文件。

以上是标准定义，简单来说：

- EI：增删改接口
- EQ：查询接口
- EO: 复杂报表，统计接口
- ILF：模型/表
- EIF：外部接口

== 功能点评估取值依据

=== 度量数据功能

ILF和EIF的复杂度分级表：

- 横向为：DET，数据元素类型（Data Element Types，简称DETs）是指在一个ILF 或EIF 内，用户可认知的、唯一的、非重复的字段。字段数
- 竖向为：RET，记录元素类型（Record Element Types，简称 RETs）是指在一个ILF 或EIF 内，用户可认知的数据元素子集。内嵌模型数

|===
|DET-RET|1-19|20-50|>=51

|1|低|低|平均
|2-5|低|平均|高
|>=6|平均|高|高
|===

|===
|功能复杂度|ILF|EIF

|低|7|5
|中|10|7
|高|15|10
|===

=== 度量事务功能

==== EI贡献度

- 横向为：DET，数据元素类型（Data Element Types，简称DET）是指在一个EI、EO 或EQ 内，用户可认知的、唯一的、非重复的字段。字段数
- 竖向为：FTR，引用文件类型（File Types Referenced，简称FTR）是指一个交易功能读取或维护的一个ILF，或者一个交易功能所读取的一个EIF。内嵌模型数

|===
|DET-FTR|1-4|5-15|>=16

|0-1|低|低|中
|2|低|中|高
|>=3|中|高|高
|===

==== EQ/EO贡献度

|===
|DET-FTR|1-5|6-19|>=20

|0-1|低|低|中
|2-3|低|中|高
|>=4|中|高|高
|===

|===
|贡献度分布|EI/EQ|EO

|低|3|4
|中|4|5
|高|6|7
|===

== 计算未调整功能点

UFP= ILFs+EIFs+EIs+EOs+EQs

== 调整系数



== 软件开发生产率基准

即每个功能点需要多少人时，可计算出总计人时，对应可计算人日及人月等数据

